import Head from "next/head";
import Header from "@/components/Layout/Header";
import Container from "@/components/Layout/Container";
import Rectangle from "@/components/Layout/Rectangle";
import Hero from "@/components/Layout/Index/Hero";
import FeatureProject from "@/components/Layout/Index/FeatureProject";
import GapContainer from "@/components/Layout/GapContainer";
import ProjectShowcase from "@/components/Layout/Index/ProjectShowcase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <div className="relative overflow-hidden">
          <Rectangle className={"-top-[10%] -left-[15%]"} />
          <Container>
            <Header />
            <Hero />
            <GapContainer>
              <FeatureProject />
              <FeatureProject flipCard={"true"} />
              <ProjectShowcase />
              <div className="h-[768px] w-full flex items-center justify-center">
                <div className="w-1/2">
                  <div>
                    <p>Experiance</p>
                    <h2>
                      My Professional <br />
                      Experiance
                    </h2>
                  </div>
                  <div>
                    <div>
                      <button></button>
                      <p>Linux System Administrator</p>
                    </div>
                    <p>School of Freelancing (Comilla,Bangladesh)</p>
                    <p>May 2020- Present</p>
                    <hr />
                    <p>
                      Configure & deploy web applications based on the LEMP and
                      LAMP stacks. Troubleshoot various production environment
                      issues. Training new candidates on various system
                      administration processes
                    </p>
                  </div>
                </div>
              </div>
            </GapContainer>
          </Container>
        </div>
      </div>
    </>
  );
}
