import Head from "next/head";
import Header from "@/components/Layout/Header";
import Container from "@/components/Layout/Container";
import Rectangle from "@/components/Layout/Rectangle";
import Hero from "@/components/Layout/Index/Hero";
import FeatureProject from "@/components/Layout/Index/FeatureProject";
import GapContainer from "@/components/Layout/GapContainer";
import ProjectShowcase from "@/components/Layout/Index/ProjectShowcase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <div className="relative overflow-hidden">
          <Rectangle className={"-top-[10%] -left-[15%]"} />
          <Container>
            <Header />
            <Hero />
            <GapContainer>
              <FeatureProject />
              <FeatureProject flipCard={"true"} />
              <ProjectShowcase />
              <div className="h-[768px] w-full flex items-center justify-center">
                <div className="w-[1005px] flex flex-col gap-[68px]">
                  <div className="text-center">
                    <p className="text-secondery text-2xl">Experiance</p>
                    <h2 className="text-projectsTitle font-bold text-56">
                      My Professional <br />
                      Experiance
                    </h2>
                  </div>
                  <div className="flex gap-[55px]">
                    <div className="p-5 border border-solid border-primary-border rounded-[10px]">
                      <div className="flex gap-4">
                        <button>*</button>
                        <p>Linux System Administrator</p>
                      </div>
                      <p className="text-primary-border">
                        School of Freelancing (Comilla,Bangladesh)
                      </p>
                      <p className="text-primary-border">May 2020- Present</p>
                      <hr className="border-primary-border" />
                      <p className="text-primary-border">
                        Configure & deploy web applications based on the LEMP
                        and LAMP stacks. Troubleshoot various production
                        environment issues. Training new candidates on various
                        system administration processes
                      </p>
                    </div>
                    <div className="p-5 border border-solid border-primary-border rounded-[10px]">
                      <div className="flex gap-4">
                        <button>*</button>
                        <p>Linux System Administrator</p>
                      </div>
                      <p className="text-primary-border">
                        School of Freelancing (Comilla,Bangladesh)
                      </p>
                      <p className="text-primary-border">May 2020- Present</p>
                      <hr className="border-primary-border" />
                      <p className="text-primary-border">
                        Configure & deploy web applications based on the LEMP
                        and LAMP stacks. Troubleshoot various production
                        environment issues. Training new candidates on various
                        system administration processes
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </GapContainer>
          </Container>
        </div>
      </div>
    </>
  );
}
